### ISSUE TITLE
언어 관련 

### ISSUE THREAD

**Issue by HappyAndJust** [BaeHyeonWoo-1017/BaeHyeonWooPL#6]
코틀린 배우고있어서 앞으로 플긴은 코틀린으로 짤거같은데 이프로젝트는 자바로할까요? 아니면 코틀린으로해도 상관없나요

**Comment by BaeHyeonWoo-1017** [comment]
바꾸려고 시도 해보시고

안되면 말고

Gradle로 컴파일 되면 편리할듯.

혹여나모르기에 이슈는 계속 열어둠
